var files =
[
    [ "src/sys/kernel.c", "kernel_8c.html", "kernel_8c" ],
    [ "src/sys/keyboard.h", "keyboard_8h.html", null ],
    [ "src/sys/terminal.c", "terminal_8c.html", "terminal_8c" ],
    [ "src/sys/terminal.h", "terminal_8h.html", "terminal_8h" ],
    [ "src/sys/arch/arch.h", "arch_8h.html", "arch_8h" ],
    [ "src/sys/arch/i686/apic.c", "apic_8c.html", "apic_8c" ],
    [ "src/sys/arch/i686/apic.h", "apic_8h.html", "apic_8h" ],
    [ "src/sys/arch/i686/arch.c", "arch_8c.html", "arch_8c" ],
    [ "src/sys/arch/i686/irq.c", "irq_8c.html", "irq_8c" ],
    [ "src/sys/arch/i686/irqdefs.h", "irqdefs_8h.html", "irqdefs_8h" ],
    [ "src/sys/arch/i686/isr.h", "isr_8h.html", "isr_8h" ],
    [ "src/sys/arch/i686/Makefile.inc", "_makefile_8inc.html", null ],
    [ "src/sys/arch/i686/paging.c", "paging_8c.html", "paging_8c" ],
    [ "src/sys/arch/i686/paging.h", "paging_8h.html", "paging_8h" ],
    [ "src/sys/arch/i686/pic.c", "pic_8c.html", "pic_8c" ],
    [ "src/sys/arch/i686/pic.h", "pic_8h.html", "pic_8h" ],
    [ "src/sys/arch/i686/pit.c", "pit_8c.html", "pit_8c" ],
    [ "src/sys/arch/i686/pit.h", "pit_8h.html", "pit_8h" ],
    [ "src/sys/arch/i686/tables.c", "tables_8c.html", "tables_8c" ],
    [ "src/sys/arch/i686/tables.h", "tables_8h.html", "tables_8h" ],
    [ "src/sys/arch/i686/timer.h", "timer_8h.html", null ],
    [ "src/sys/arch/i686/util.h", "util_8h.html", "util_8h" ],
    [ "src/sys/pci/identifiers.h", "identifiers_8h.html", "identifiers_8h" ],
    [ "src/sys/video/vga.h", "vga_8h.html", null ]
];